"""Added Column To User Entity

Revision ID: 81673e96af25
Revises: 39ea454b9544
Create Date: 2021-11-16 13:51:25.109457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81673e96af25'
down_revision = '39ea454b9544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('user_id', sa.String(length=128), nullable=False))
    op.add_column('USER', sa.Column('user_name', sa.String(length=20), nullable=False))
    op.add_column('USER', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index('email', table_name='USER')
    op.create_unique_constraint(None, 'USER', ['user_id'])
    op.drop_column('USER', 'email')
    op.drop_column('USER', 'nick_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('nick_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False))
    op.add_column('USER', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False))
    op.drop_constraint(None, 'USER', type_='unique')
    op.create_index('email', 'USER', ['email'], unique=False)
    op.drop_column('USER', 'created_at')
    op.drop_column('USER', 'user_name')
    op.drop_column('USER', 'user_id')
    # ### end Alembic commands ###
